booking/urls.py
from django.urls import path 
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("delete_session/", views.delete_session, name="delete_session"),
    path("booking_data/<slug:slug>/", views.booking_data, name="booking_data"),

    # Ajax
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
]

hotel/urls.py
from django.urls import path 
from hotel import views 

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug:slug>/", views.hotel_detail, name="detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("invoice/<booking_id>/", views.invoice, name="invoice"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
    # Payment API
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from  django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps Routes
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("user_dashboard.urls")),


    #path("media/)", serve,{'document_root': settings.MEDIA_ROOT}),
    #path("static/)", serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]


#if settings.DEBUG:
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hotel/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.conf import settings
from django.urls import reverse
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives



from hotel.models import Coupon, CouponUsers, Hotel, Room, Booking, RoomServices, HotelGallery, HotelFeatures, RoomType, Notification, Bookmark, Review

from datetime import datetime
from decimal import Decimal
import stripe
import json


def index(request):
    hotel = Hotel.objects.filter(status="Live")
    context = {
        "hotel":hotel
    }
    return render(request, "hotel/index.html", context)


def hotel_detail(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    try:
        reviews = Review.objects.filter(user=request.user, hotel=hotel)
    except:
        reviews = None
    all_reviews = Review.objects.filter(hotel=hotel, active=True)
    
    if request.user.is_authenticated:
        bookmark = Bookmark.objects.filter(user=request.user, hotel=hotel)
    else:
        bookmark = None
    context = {
        "hotel":hotel,
        "bookmark":bookmark,
        "reviews":reviews,
        "all_reviews":all_reviews,
    }
    return render(request, "hotel/hotel_detail.html", context)


def room_type_detail(request, slug, rt_slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    room_type = RoomType.objects.get(hotel=hotel, slug=rt_slug)
    rooms = Room.objects.filter(room_type=room_type, is_available=True)

    id = request.GET.get("hotel-id")
    checkin = request.GET.get("checkin")
    checkout = request.GET.get("checkout")
    adult = request.GET.get("adult")
    children = request.GET.get("children")
    room_type_ = request.GET.get("room-type")

    print("checkin ======", checkin)

    if not all([checkin, checkout]):
        messages.warning(request, "Please enter your booking data to check availability.")
        return redirect("booking:booking_data", hotel.slug)

    context = {
        "hotel":hotel,
        "room_type":room_type,
        "rooms":rooms,
        "id":id,
        "checkin":checkin,
        "checkout":checkout,
        "adult":adult,
        "children":children,
        "room_type_":room_type_,
    }
    return render(request, "hotel/room_type_detail.html", context)



def selected_rooms(request):
    # request.session.pop('selection_data_obj', None)

    total = 0
    room_count = 0
    total_days = 0
    adult = 0 
    children = 0 
    checkin = "0" 
    checkout = "" 
    children = 0 
    
    if 'selection_data_obj' in request.session:

        if request.method == "POST":
            for h_id, item in request.session['selection_data_obj'].items():
                
                id = int(item['hotel_id'])
                hotel_id = int(item['hotel_id'])

                checkin = item["checkin"]
                checkout = item["checkout"]
                adult = int(item["adult"])
                children = int(item["children"])
                room_type_ = item["room_type"]
                room_id = int(item["room_id"])
                
                user = request.user
                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)

                

                
            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            full_name = request.POST.get("full_name")
            email = request.POST.get("email")
            phone = request.POST.get("phone")

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                check_in_date=checkin,
                check_out_date=checkout,
                total_days=total_days,
                num_adults=adult,
                num_children=children,
                full_name=full_name,
                email=email,
                phone=phone
            )

            if request.user.is_authenticated:
                booking.user = request.user
                booking.save()
            else:
                booking.user = None
                booking.save()


            for h_id, item in request.session['selection_data_obj'].items():
                room_id = int(item["room_id"])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count += 1
                days = booking.total_days
                price = booking.room_type.price

                room_price = price * room_count
                total = room_price * days

                # print("room_price ==",room_price)
                # print("total ==",total)
            
            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            messages.success(request, "Checkout Now!")
            return redirect("hotel:checkout", booking.booking_id)

        hotel = None

        for h_id, item in request.session['selection_data_obj'].items():
                
            id = int(item['hotel_id'])
            hotel_id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult = int(item["adult"])
            children = int(item["children"])
            room_type_ = item["room_type"]
            room_id = int(item["room_id"])
            
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days
            
            hotel = Hotel.objects.get(id=id)

        print("hotel ===", hotel)
        context = {
            "data":request.session['selection_data_obj'], 
            "total_selected_items": len(request.session['selection_data_obj']),
            "total":total,
            "total_days":total_days,
            "adult":adult,
            "children":children,   
            "checkin":checkin,   
            "checkout":checkout,   
            "hotel":hotel,   
        }

        return render(request, "hotel/selected_rooms.html", context)
    else:
        messages.warning(request, "You don't have any room selections yet!")
        return redirect("/")

def checkout(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)

    if booking.payment_status == "paid":
        messages.success(request, "This order has been paid for!")
        return redirect("/")
    else:
        booking.payment_status = "processing"
        booking.save()


    # Coupon
    now = timezone.now()
    if request.method == "POST":
        # Get code entered in the input field
        code = request.POST.get('code')
        print("code ======", code)
        try:
            coupon = Coupon.objects.get(code__iexact=code,valid_from__lte=now,valid_to__gte=now,active=True)
            if coupon in booking.coupons.all():
                messages.warning(request, "Coupon Already Activated")
                return redirect("hotel:checkout", booking.booking_id)
            else:
                CouponUsers.objects.create(
                    booking=booking,
                    coupon=coupon,
                    full_name=booking.full_name,
                    email=booking.email,
                    mobile=booking.phone,
                )

                if coupon.type == "Percentage":
                    discount = booking.total * coupon.discount / 100
                else:
                    discount = coupon.discount

                booking.coupons.add(coupon)
                booking.total -= discount
                booking.saved += discount
                booking.save()

                
                messages.success(request, "Coupon Found and Activated")
                return redirect("hotel:checkout", booking.booking_id)
        except Coupon.DoesNotExist:
            messages.error(request, "Coupon Not Found")
            return redirect("hotel:checkout", booking.booking_id)
    
    context = {
        "booking":booking,  
        "stripe_publishable_key":settings.STRIPE_PUBLIC_KEY,
        "flutter_publick_key":settings.FLUTTERWAVE_PUBLIC,
        "website_address":settings.WEBSITE_ADDRESS,
    }
    return render(request, "hotel/checkout.html", context)


@csrf_exempt
def create_checkout_session(request, booking_id):
    request_data = json.loads(request.body)
    booking = get_object_or_404(Booking, booking_id=booking_id)

    stripe.api_key = settings.STRIPE_PRIVATE_KEY
    checkout_session = stripe.checkout.Session.create(
        customer_email = booking.email,
        payment_method_types=['card'],
        line_items=[
            {
                'price_data': {
                    'currency': 'usd',
                    'product_data': {
                    'name': booking.full_name,
                    },
                    'unit_amount': int(booking.total * 100),
                },
                'quantity': 1,
            }
        ],
        mode='payment',

templates/hotel/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
<div id="main_wrapper">
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>All Room Selections</h2>
          <nav id="breadcrumbs">
            <ul>
              <li><a>Home</a></li>
              <li><a>Hotel</a></li>
              <li><a>Rooms</a></li>
              <li>My selected rooms</li>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container margin-bottom-75">
    <div class="row">
      <div class="col-lg-8 col-md-8 utf_listing_payment_section">
	    <div class="notification warning closeable">
			<p><span>NOTE!</span> Review your order before payment.</p>
			<a class="close" href="#"></a> 
		  </div>
        <div class="utf_booking_listing_section_form margin-bottom-40">
            <h3><i class="fas fa-bed"></i> Selected Rooms</h3>
            <div class="utf_listing_section">
                    <div class="utf_pricing_list_section">
                        <ul>
                            {% for r in booking.room.all %}
                                <li>
                                    <h5>Room: {{r.room_type.type}} </h5>
                                    <p><strong>Beds :</strong> {{r.number_of_beds}}  </p>
                                    <span>${{r.room_type.price}} </span>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
            </div>
        </div>
            
        <div class="utf_booking_listing_section_form margin-bottom-40">
		  <h3><i class="fas fa-user"></i> Billing Information</h3>
			<div class="row">
			  <div class="col-md-12">
				<label>First Name</label>
				<input name="full_name" type="text" value="{{booking.full_name}}" readonly placeholder="First Name">
			  </div>
			  <div class="col-md-6">
				<div class="medium-icons">
				  <label>E-Mail</label>
				  <input name="email" id="email" type="text" value="{{booking.email}}" readonly placeholder="Email">
				</div>
			  </div>
			  <div class="col-md-6">
				<div class="medium-icons">
				  <label>Phone</label>
				  <input name="phone" type="text" value="{{booking.phone}}" readonly >
				</div>
			  </div>
              <div class="col-lg-12">
			  </div>
			</div>
		</div>

		
	  </div>
      <div class="col-lg-4 col-md-4 margin-top-0 utf_listing_payment_section">
        <div class="utf_booking_listing_item_container compact utf_order_summary_widget_section">
          <div class="listing-item"> <img src="{{booking.hotel.image.url}}" alt="">
            <div class="utf_listing_item_content">              
              <h3>{{booking.hotel.name}}</h3>
              <span><i class="fa fa-map-marker"></i> The Ritz-Carlton, Hong Kong</span>
						<span><i class="fa fa-phone"></i> (+15) 124-796-3633</span>											
			  <div class="utf_star_rating_section" data-rating="4.5">
				<div class="utf_counter_star_rating">(18) Reviews</div>
			  </div>
			</div>
          </div>
        </div>
        <div class="boxed-widget opening-hours summary margin-top-0">
          <h3><i class="fa fa-calendar-check-o"></i> Booking Summary</h3>
          <ul>
            <li>Check-in <span>{{booking.check_in_date}}</span></li>
			      <li>Check-out <span>{{booking.check_out_date}}</span></li>            
            <li>Adults <span>{{ booking.num_adults }} Adults</span></li>
            <li>Children <span>{{ booking.num_children }} Children</span></li>
			      <li>V.A.T <span>$0.00</span></li>
            
            {% if booking.saved != 0.00 %}
			      <li>Discount<span>-${{booking.saved}}</span></li>
            {% endif %}

            <li class="total-costs">
              <form action="" method="POST">
                {% csrf_token %}
                <div class="col-md-8">
                  <input id="couponCode" name="code" placeholder="Have a coupon enter here..." required="" type="text">
                </div>
                <div class="col-md-4">
                  <input type="submit" class="coupon_code" value="Apply">	
                </div>
              </form>
              <div class="clearfix"></div>
            </li>
            <li class="total-costs">Total Cost <span>${{booking.total}}</span></li>
          </ul>
          <form method="POST" action="https://checkout.flutterwave.com/v3/hosted/pay">
               <input type="hidden" name="public_key" value="FLWPUBK_TEST-a2c377d3cf56b37b9e660f85e26d2f8f-X" />
               <input type="hidden" name="customer[email]" value="{{booking.email}}" />
               <input type="hidden" name="customer[name]" value="{{booking.full_name}}" />
               <input type="hidden" name="tx_ref" value="ID-{{booking.booking_id}}" />
               <input type="hidden" name="amount" value="{{booking.total}}" />
               <input type="hidden" name="currency" value="USD" />
               <input type="hidden" name="meta[token]" value="54" />
               <input type="hidden" name="redirect_url" value="{{website_address}}/success/{{booking.booking_id}}/?success_id={{booking.success_id}}&booking_total={{booking.total}}" />
               
               <button id="flutter-btn" class="button utf_booking_confirmation_button margin-top-20 w-100 " style="background-color: orange; color: rgb(37, 28, 3);">Pay with Flutterwave <img src="https://asset.brandfetch.io/iddYbQIdlK/idmlgmHt_3.png" style="width: 40px;" alt=""></button> 		
          </form>
          <button id="checkout-button" class="button utf_booking_confirmation_button margin-top-10 margin-bottom-10 w-100">Pay with Stripe <i class="fas fa-credit-card"></i></button> 		
          <div id="paypal-button-container"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id=test&currency=USD"></script>
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://js.stripe.com/v3/"></script>

<script type="text/javascript">



    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout-button');

    checkoutButton.addEventListener('click', function () {

        var email = document.getElementById('email').value;
        if (email.length == 0) {
            alert("Please enter your email address.");
            return;
        }

        checkoutButton.innerHTML = "Starting..."
        
        fetch("{% url 'hotel:api_checkout_session' booking_id=booking.booking_id %}", {
            method: 'POST',
            body: JSON.stringify(
                { email: email }
            )
        }).then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>


<script>
   booking_id = "{{booking.booking_id}}"
   booking_total = "{{booking.total}}"
   success_id = "{{booking.success_id}}"
   id = "{{booking.id}}"

   paypal.Buttons({

      createOrder: function(data, actions) {
         return actions.order.create({
            purchase_units: [{
               amount: {
                  value: booking_total
               }
            }]
         })
      },

       onApprove: function(data, actions) {
           return actions.order.capture().then(function(Details){
              window.location.href = "/success/"+ booking_id +"/?PayerID="+ id +"&success_id=" + success_id + "&booking_total=" + booking_total + "/" ; 
           })
       }

   }).render('#paypal-button-container');
</script>

<script>
  let flutter_btn = document.getElementById("flutter-btn")
  flutter_btn.addEventListener("click", function(){
    flutter_btn.innerHTML = "Starting..."
  })
</script>
  
{% endblock content %}

templates/hotel/index.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
        <!-- Banner -->
        <div class="search_container_block main_search_block" data-background-image="{% static 'images/home_section_1.jpg' %}">
            <div class="main_inner_search_block">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h2>Book Unique Experiences</h2>
                            <h4>Discover top rated hotels, shops and restaurants around the world</h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="fullwidth_block margin-top-65 padding-top-75 padding-bottom-70" data-background-color="#f9f9f9">
            <div class="container">
                <div class="row slick_carousel_slider">
                    <div class="col-md-12">
                        <h3 class="headline_part centered margin-bottom-45">Our Popular Tours <span>Explore the greates places in the city</span> </h3>
                    </div>

                    <div class="row">
                       
                                {% for h in hotel %}
                                    <div class="col-lg-4">
                                        <a href="{% url 'hotel:detail' h.slug %}" class="utf_listing_item-container compact">
                                            <div class="utf_listing_item"> <img src="{{h.image.url}}" alt=""> 
                                                <!-- <span class="tag"> <i class="im im-icon-Chef-Hat"></i> Restaurant </span>  -->
                                                <!-- <span class="featured_tag">Featured</span> -->
                                                <span class="utf_open_now">Open Now</span>
                                                <div class="utf_listing_item_content">
                                                    <div class="utf_listing_prige_block">
                                                        <!-- <span class="utf_meta_listing_price"><i class="fa fa-tag"></i> $25 - $55</span> -->
                                                        <!-- <span class="utp_approve_item"><i class="utf_approve_listing"></i></span> -->
                                                    </div>
                                                    <h3>{{h.name|truncatechars:20}}</h3>
                                                    <span><i class="fas fa-location-arrow"></i> {{h.address}}</span>
                                                    <span><i class="fas fa-phone"></i> {{h.mobile}}</span>
                                                </div>
                                            </div>
                                            <div class="utf_star_rating_section" data-rating="{{h.average_rating}}">
                                                
                                                {% if h.average_rating == None %}
                                                <div class="utf_counter_star_rating">No Rating Yet</div>
                                                {% else %}
                                                <div class="utf_counter_star_rating">{{h.average_rating}}/5 ({{h.rating_count}} reviews) </div>
                                                {% endif %}
                                                    
                                                <span class="utf_view_count"> {{h.views}}</span>
                                                <span class="like-icon add-to-bookmark-{{h.id}}" data-hotel="{{h.id}}" id="add-to-bookmark"></span>
                                            </div>
                                        </a>
                                    </div>
                                {% endfor %}

                               
                            
                    </div>
                </div>
            </div>
        </section>


        <section class="utf_testimonial_part fullwidth_block padding-top-75 padding-bottom-75">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h3 class="headline_part centered"> What Say Our Customers <span class="margin-top-15"></span> </h3>
                    </div>
                </div>
            </div>
            <div class="fullwidth_carousel_container_block margin-top-20">
                <div class="utf_testimonial_carousel testimonials">
                    <div class="utf_carousel_review_part">
                        <div class="utf_testimonial_box">
                            <div class="testimonial">Booking my hotel through this website was a breeze! I found exactly what I needed quickly, and the whole process was smooth from start to finish. The pictures and descriptions were accurate, 
                                and the booking confirmation came through promptly. Overall, a fantastic experience!</div>
                        </div>
                        <div class="utf_testimonial_author"> <img src="{% static 'images/happy-client-01.jpg' %}" alt="">
                            <h4>Dkavindu <span>Web Developer</span></h4>
                        </div>
                    </div>
                    <div class="utf_carousel_review_part">
                        <div class="utf_testimonial_box">
                            <div class="testimonial">Booking my hotel through this website was a breeze! I found exactly what I needed quickly, and the whole process was smooth from start to finish. The pictures and descriptions were accurate, 
                                and the booking confirmation came through promptly. Overall, a fantastic experience!</div>
                        </div>
                        <div class="utf_testimonial_author"> <img src="{% static 'images/happy-client-02.jpg' %}" alt="">
                            <h4>Dkavindu <span>Web Developer</span></h4>
                        </div>
                    </div>
                    <div class="utf_carousel_review_part">
                        <div class="utf_testimonial_box">
                            <div class="testimonial">Booking my hotel through this website was a breeze! I found exactly what I needed quickly, and the whole process was smooth from start to finish. The pictures and descriptions were accurate, 
                                and the booking confirmation came through promptly. Overall, a fantastic experience!</div>
                        </div>
                        <div class="utf_testimonial_author"> <img src="{% static 'images/happy-client-03.jpg' %}" alt="">
                            <h4>Dkavindu <span>Project Manager</span></h4>
                        </div>
                    </div>
                    <div class="utf_carousel_review_part">
                        <div class="utf_testimonial_box">
                            <div class="testimonial">Booking my hotel through this website was a breeze! I found exactly what I needed quickly, and the whole process was smooth from start to finish. The pictures and descriptions were accurate, 
                                and the booking confirmation came through promptly. Overall, a fantastic experience!</div>
                        </div>
                        <div class="utf_testimonial_author"> <img src="{% static 'images/happy-client-01.jpg' %}" alt="">
                            <h4>Dkavindu <span>Web Developer</span></h4>
                        </div>
                    </div>
                </div>
            </div>
        </section>


        <div class="fullwidth_block margin-bottom-0 padding-top-50 padding-bottom-50" data-background-color="linear-gradient(to bottom, #f9f9f9 0%, rgba(255, 255, 255, 1))">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="companie-logo-slick-carousel utf_dots_nav">
                            <div class="item">
                                <img src="{% static 'images/brand_logo_01.png' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'images/brand_logo_02.png' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'images/brand_logo_03.png' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'images/brand_logo_04.png' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'images/brand_logo_05.png' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'images/brand_logo_06.png' %}" alt="">
                            </div>
                            <div class="item">
                                <img src="{% static 'images/brand_logo_07.png' %}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <section class="utf_cta_area_item utf_cta_area2_block">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="utf_subscribe_block clearfix">
                            <div class="col-md-8 col-sm-7">
                                <div class="section-heading">
                                    <h2 class="utf_sec_title_item utf_sec_title_item2">Subscribe to Newsletter!</h2>
                                    <p class="utf_sec_meta">
                                        Subscribe to get latest updates and information.
                                    </p>
                                </div>
                            </div>
                            <div class="col-md-4 col-sm-5">
                                <div class="contact-form-action">
                                    <form method="post">
                                        <span class="la la-envelope-o"></span>
                                        <input class="form-control" type="email" placeholder="Enter your email" required="">
                                        <button class="utf_theme_btn" type="submit">Subscribe</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

{% endblock content %}
    