hotel/urls.py
from django.urls import path 
from hotel import views 

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug:slug>/", views.hotel_detail, name="detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("invoice/<booking_id>/", views.invoice, name="invoice"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
    # Payment API
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from  django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps Routes
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("user_dashboard.urls")),


    #path("media/)", serve,{'document_root': settings.MEDIA_ROOT}),
    #path("static/)", serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]


#if settings.DEBUG:
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_dashboard/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views

from user_dashboard import views


app_name = "dashboard"


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("booking-detail/<booking_id>/", views.booking_detail, name="booking_detail"),
    path("bookings/", views.bookings, name="bookings"),
    path("notifications/", views.notifications, name="notifications"),
    path("wallet/", views.wallet, name="wallet"),
    path("bookmark/", views.bookmark, name="bookmark"),
    path("delete_bookmark/<bid>/", views.delete_bookmark, name="delete_bookmark"),
    path("profile/", views.profile, name="profile"),

    # Change Password View
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user_dashboard/password-reset/change-password.html',success_url = '/dashboard/password-changed/'),name='change_password'),
    path("password-changed/", views.password_changed, name="password_changed"),


    # Ajax
    path("notification_filter/", views.notification_filter, name="notification_filter"),
    path("notification_mark_as_seen/", views.notification_mark_as_seen, name="notification_mark_as_seen"),
    path("add_to_bookmark/", views.add_to_bookmark, name="add_to_bookmark"),
    path("add_review/", views.add_review, name="add_review"),

]

userauths/urls.py
from django.urls import path 
from userauths import views 

app_name = "userauths"

urlpatterns = [
    path("sign-up/", views.RegisterView, name="sign-up"),
    path("sign-in/", views.loginViewTemp, name="sign-in"),
    path("sign-out/", views.LogoutView, name="sign-out"),
]

templates/partials/dashboard_base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta name="author" content="">
    <meta name="description" content="">
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboard</title>

    <!-- Favicon -->
    <link rel="shortcut icon" href="images/favicon.png">
    <!-- Style CSS -->
    <link rel="stylesheet" href="{% static 'css/stylesheet.css' %}">
    <link rel="stylesheet" href="{% static 'css/mmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/perfect-scrollbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" id="colors">
    <!-- Google Font -->
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800&display=swap&subset=latin-ext,vietnamese" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" />
    <!-- <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script> -->
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">     -->
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@mdi/font@7.2.96/css/materialdesignicons.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/remixicon-ligatures@2.5.0/fonts/remixicon.min.css">
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.2.0/fonts/remixicon.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://unpkg.com/sweetalert2@7.8.2/dist/sweetalert2.all.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://smtpjs.com/v3/smtp.js"></script> 
    <link href="https://fonts.googleapis.com/css?family=Nunito:300,400,600,700,800&display=swap&subset=latin-ext,vietnamese" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,500,600,700,800" rel="stylesheet" type="text/css">

</head>

<body>
    <!-- Wrapper -->
    <div id="main_wrapper">
        <header id="header_part" class="fixed fullwidth_block dashboard">
            <div id="header" class="not-sticky">
                <div class="container">
                    <div class="utf_left_side">
                        <div id="logo"> <a href="{% url 'dashboard:dashboard' %}"><img src="{% static 'images/logo.png' %}" alt=""></a> <a href="{% url 'dashboard:dashboard' %}" class="dashboard-logo"><img src="{% static 'images/logo2.png' %}" alt=""></a> </div>
                        <div class="mmenu-trigger">
                            <button class="hamburger utfbutton_collapse" type="button">
                                <span class="utf_inner_button_box">
                                    <span class="utf_inner_section"></span>
                                </span>
                            </button>
                        </div>
                        <nav id="navigation" class="style_one">
                            <ul id="responsive">
                                <li><a href="{% url 'dashboard:dashboard' %}"> <i class="bi bi-grid"></i> Dashboard</a></li>
                            </ul>
                        </nav>
                        <div class="clearfix"></div>
                    </div>
                    <div class="utf_right_side">
                        <div class="header_widget">
                            <div class="dashboard_header_button_item {% if noti %} has-noti {% endif %} js-item-menu">
                                <i class="fas fa-bell"></i>
                                <div class="dashboard_notifi_dropdown js-dropdown">
                                    <div class="dashboard_notifi_title">
                                        <p>You Have {{noti.count}} Notifications</p>
                                    </div>
                                    
                                    {% for n in noti %}
                                        <div class="dashboard_notifi_item">
                                            <div class="bg-c1 red">
                                                <i class="fas fa-check"></i>
                                            </div>
                                            <div class="content">
                                                
                                                {% if n.type == "Booking Confirmed" %}
                                                    <p>Your booking <b>(#{{n.booking.booking_id}})</b> has been placed successfully.</p>
                                                {% endif %}
                                                <span class="date">{{n.date|timesince}} ago</span>
                                            </div>
                                        </div>
                                    {% endfor %}
                                    
                                    {% if noti %}
                                        <div class="dashboard_notify_bottom text-center pad-tb-20">
                                            <a href="{% url 'dashboard:notifications' %}">View All Notifications</a>
                                        </div>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="utf_user_menu">
                                <div class="utf_user_name"><span><img src="{{request.user.profile.image.url}}" alt=""></span>Hi, {{request.user.username|title}}!</div>
                                <ul>
                                    <li><a href="{% url 'dashboard:dashboard' %}">Dashboard</a></li>
                                    <li><a href="{% url 'dashboard:dashboard' %}"> My Profile</a></li>
                                    <li><a href="{% url 'dashboard:bookings' %}">Boking</a></li>
                                    <li><a href="{% url 'dashboard:wallet' %}">Wallet</a></li>
                                    <li><a href="{% url 'dashboard:bookmark' %}">Bookmarks</a></li>
                                    <li><a href="{% url 'dashboard:notifications' %}">Notifications</a></li>
                                    <li><a href="{% url 'userauths:sign-out' %}">Logout</a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </header>
        <div class="clearfix"></div>
        
        {% block content %}
            
        {% endblock content %}
            
    </div>

    <!-- Scripts -->
    <script src="{% static 'scripts/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'scripts/chosen.min.js' %}"></script>
    <script src="{% static 'scripts/perfect-scrollbar.min.js' %}"></script>
    <script src="{% static 'scripts/slick.min.js' %}"></script>
    <script src="{% static 'scripts/rangeslider.min.js' %}"></script>
    <script src="{% static 'scripts/magnific-popup.min.js' %}"></script>
    <script src="{% static 'scripts/jquery-ui.min.js' %}"></script>
    <script src="{% static 'scripts/mmenu.js' %}"></script>
    <script src="{% static 'scripts/tooltips.min.js' %}"></script>
    <script src="{% static 'scripts/color_switcher.js' %}"></script>
    <script src="{% static 'scripts/jquery_custom.js' %}"></script>
    <script src="{% static 'scripts/custom.js' %}"></script>
    <script>
        (function($) {
            try {
                var jscr1 = $('.js-scrollbar');
                if (jscr1[0]) {
                    const ps1 = new PerfectScrollbar('.js-scrollbar');

                }
            } catch (error) {
                console.log(error);
            }
        })(jQuery);
    </script>
    
</body>

</html>

templates/partials/dashboard_sidebar.html
{% load static %}

<div class="utf_dashboard_navigation js-scrollbar">
    <div class="utf_dashboard_navigation_inner_block">
        <ul>
            <li class="{% if request.path == '/dashboard/' %}  active {% endif %}"><a href="{% url 'dashboard:dashboard' %}"><i class="bi bi-grid"></i> Dashboard</a></li>
            <li class="{% if request.path == '/dashboard/bookings/'  %}  active {% endif %}"><a href="{% url 'dashboard:bookings' %}"><i class="bi bi-check"></i>All Bookings</a></li>
            <li class="{% if request.path == '/dashboard/notifications/'  %}  active {% endif %}"><a href="{% url 'dashboard:notifications' %}"><i class="bi bi-bell-fill"></i> Notifications</a></li>
            <li class="{% if request.path == '/dashboard/wallet/'  %}  active {% endif %}"><a href="{% url 'dashboard:wallet' %}"><i class="bi bi-wallet-fill"></i> Wallet</a></li>
            <li class="{% if request.path == '/dashboard/bookmark/'  %}  active {% endif %}"><a href="{% url 'dashboard:bookmark' %}"><i class="bi bi-heart-fill"></i> Bookmark</a></li>
            <li class="{% if request.path == '/dashboard/profile/'  %}  active {% endif %}"><a href="{% url 'dashboard:profile' %}"><i class="bi bi-person-fill"></i> My Profile</a></li>
            <li class="{% if request.path == '/dashboard/change-password/'  %}  active {% endif %}"><a href="{% url 'dashboard:change_password' %}"><i class="bi bi-lock-fill"></i> Change Password</a></li>
            <li><a href="{% url 'userauths:sign-out' %}"><i class="bi bi-arrow-left"></i> Logout</a></li>

        </ul>
    </div>
</div>