booking/urls.py
from django.urls import path 
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("delete_session/", views.delete_session, name="delete_session"),
    path("booking_data/<slug:slug>/", views.booking_data, name="booking_data"),

    # Ajax
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
]

hotel/urls.py
from django.urls import path 
from hotel import views 

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug:slug>/", views.hotel_detail, name="detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("invoice/<booking_id>/", views.invoice, name="invoice"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
    # Payment API
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from  django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps Routes
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("user_dashboard.urls")),


    #path("media/)", serve,{'document_root': settings.MEDIA_ROOT}),
    #path("static/)", serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]


#if settings.DEBUG:
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_dashboard/urls.py
from django.urls import path 
from django.contrib.auth import views as auth_views

from user_dashboard import views


app_name = "dashboard"


urlpatterns = [
    path("", views.dashboard, name="dashboard"),
    path("booking-detail/<booking_id>/", views.booking_detail, name="booking_detail"),
    path("bookings/", views.bookings, name="bookings"),
    path("notifications/", views.notifications, name="notifications"),
    path("wallet/", views.wallet, name="wallet"),
    path("bookmark/", views.bookmark, name="bookmark"),
    path("delete_bookmark/<bid>/", views.delete_bookmark, name="delete_bookmark"),
    path("profile/", views.profile, name="profile"),

    # Change Password View
    path('change-password/',auth_views.PasswordChangeView.as_view(template_name='user_dashboard/password-reset/change-password.html',success_url = '/dashboard/password-changed/'),name='change_password'),
    path("password-changed/", views.password_changed, name="password_changed"),


    # Ajax
    path("notification_filter/", views.notification_filter, name="notification_filter"),
    path("notification_mark_as_seen/", views.notification_mark_as_seen, name="notification_mark_as_seen"),
    path("add_to_bookmark/", views.add_to_bookmark, name="add_to_bookmark"),
    path("add_review/", views.add_review, name="add_review"),

]

booking/models.py
from django.db import models

# Create your models here.

user_dashboard/models.py
from django.db import models

# Create your models here.

booking/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.template.loader import render_to_string


from hotel.models import Hotel, Room, Booking, RoomServices, HotelGallery, HotelFeatures, RoomType

from datetime import datetime
from decimal import Decimal

def check_room_availability(request):
    if request.method == "POST":
        id = request.POST.get("hotel-id")
        checkin = request.POST.get("checkin")
        checkout = request.POST.get("checkout")
        adult = request.POST.get("adult")
        children = request.POST.get("children")
        room_type = request.POST.get("room-type")

        hotel = Hotel.objects.get(status="Live", id=id)
        room_type = RoomType.objects.get(hotel=hotel, slug=room_type)
        
        print("id ====", id)
        print("room_type ====", room_type)
        print("checkin ====", checkin)
        print("checkout ====", checkout)
        print("adult ====", adult)
        print("children ====", children)

        # return redirect("hotel:room_type_detail", hotel.slug, room_type.slug)
        url = reverse("hotel:room_type_detail", args=[hotel.slug, room_type.slug])
        url_with_params = f"{url}?hotel-id={id}&checkin={checkin}&checkout={checkout}&adult={adult}&children={children}&room_type={room_type}"
        return HttpResponseRedirect(url_with_params)

    else:
        return redirect("hotel:index")


def booking_data(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    context = {
        "hotel":hotel,
    }
    return render(request, "booking/booking_data.html", context)


def add_to_selection(request):
    room_selection = {}

    room_selection[str(request.GET['id'])] = {
        'hotel_id': request.GET['hotel_id'],
        'hotel_name': request.GET['hotel_name'],
        'room_name': request.GET['room_name'],
        'room_price': request.GET['room_price'],
        'number_of_beds': request.GET['number_of_beds'],
        'room_number': request.GET['room_number'],
        'room_type': request.GET['room_type'],
        'room_id': request.GET['room_id'],
        'checkin': request.GET['checkin'],
        'checkout': request.GET['checkout'],
        'adult': request.GET['adult'],
        'children': request.GET['children'],
    }

    if 'selection_data_obj' in request.session:
        if str(request.GET['id']) in request.session['selection_data_obj']:

            selection_data = request.session['selection_data_obj']
            selection_data[str(request.GET['id'])]['adult'] = int(room_selection[str(request.GET['id'])]['adult'])
            selection_data[str(request.GET['id'])]['children'] = int(room_selection[str(request.GET['id'])]['children'])
            request.session['selection_data_obj'] = selection_data
        else:
            selection_data = request.session['selection_data_obj']
            selection_data.update(room_selection)
            request.session['selection_data_obj'] = selection_data
    else:
        request.session['selection_data_obj'] = room_selection
    data = {
        "data":request.session['selection_data_obj'], 
        'total_selected_items': len(request.session['selection_data_obj'])
        }
    return JsonResponse(data)


def delete_session(request):
    request.session.pop('selection_data_obj', None)
    return redirect(request.META.get("HTTP_REFERER"))


def delete_selection(request):
    hotel_id = str(request.GET['id'])
    if 'selection_data_obj' in request.session:
        if hotel_id in request.session['selection_data_obj']:
            selection_data = request.session['selection_data_obj']
            del request.session['selection_data_obj'][hotel_id]
            request.session['selection_data_obj'] = selection_data


    total = 0
    total_days = 0
    room_count = 0
    adult = 0 
    children = 0 
    checkin = "" 
    checkout = "" 
    children = 0 
    hotel = None

    if 'selection_data_obj' in request.session:
        for h_id, item in request.session['selection_data_obj'].items():
                
            id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult += int(item["adult"])
            children += int(item["children"])
            room_type_ = item["room_type"]
            
            hotel = Hotel.objects.get(id=id)
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days
        
    
    context = render_to_string("hotel/async/selected_rooms.html", { "data":request.session['selection_data_obj'],  "total_selected_items": len(request.session['selection_data_obj']), "total":total, "total_days":total_days, "adult":adult, "children":children,    "checkin":checkin,    "checkout":checkout,    "hotel":hotel})

    print("data ======", context)
    
    return JsonResponse({"data": context, 'total_selected_items': len(request.session['selection_data_obj'])})

user_dashboard/views.py
from django.shortcuts import render, redirect
from django.db import models
from django.template.loader import render_to_string
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from hotel.models import Booking, Notification, Bookmark, Hotel, Review
from userauths.models import Profile, User
from userauths.forms import ProfileUpdateForm, UserUpdateForm

@login_required
def dashboard(request):
    bookings = Booking.objects.filter(user=request.user, payment_status="paid")
    total_spent = Booking.objects.filter(user=request.user, payment_status="paid").aggregate(amount=models.Sum('total'))

    print("bookings ========", total_spent)
    context = {
        "bookings":bookings,
        "total_spent":total_spent,
    }
    return render(request, "user_dashboard/dashboard.html", context)

@login_required
def booking_detail(request, booking_id):
    booking = Booking.objects.get(booking_id=booking_id)

    context = {
        "booking":booking,
    }
    return render(request, "user_dashboard/booking_detail.html", context)

@login_required
def bookings(request):
    bookings = Booking.objects.filter(user=request.user, payment_status="paid")

    context = {
        "bookings":bookings,
    }
    return render(request, "user_dashboard/bookings.html", context)


@login_required
def notifications(request):
    notifications = Notification.objects.filter(user=request.user, seen=False)

    context = {
        "notifications":notifications,
    }
    return render(request, "user_dashboard/notifications.html", context)

def notification_filter(request):
    query = request.GET['query']
    if query == "all":
        notifications = Notification.objects.filter(user=request.user)
    elif query == "read":
        notifications = Notification.objects.filter(user=request.user, seen=True)
    elif query == "unread":
        notifications = Notification.objects.filter(user=request.user, seen=False)
    else:
        notifications = Notification.objects.filter(user=request.user)
    
    print("notifications ===", notifications)

    context = render_to_string("user_dashboard/async/notifications.html", {"notifications":notifications})
    print("data ======", context)

    return JsonResponse({"data":context})


def notification_mark_as_seen(request):
    id = request.GET['id']
    notification = Notification.objects.get(id=id)
    notification.seen = True
    notification.save()
    
    return JsonResponse({"data":"Marked As Seen"})


@login_required
def wallet(request):
    bookings = Booking.objects.filter(user=request.user, payment_status="paid")
    total_spent = Booking.objects.filter(user=request.user, payment_status="paid").aggregate(amount=models.Sum('total'))

    context = {
        "bookings":bookings,
        "total_spent":total_spent,
    }
    return render(request, "user_dashboard/wallet.html", context)



@login_required
def bookmark(request):
    bookmark = Bookmark.objects.filter(user=request.user)

    context = {
        "bookmark":bookmark,
    }
    return render(request, "user_dashboard/bookmark.html", context)



@login_required
def delete_bookmark(request, bid):
    bookmark = Bookmark.objects.filter(bid=bid)
    bookmark.delete()
    return redirect("dashboard:bookmark")


def add_to_bookmark(request):
    id = request.GET['id']
    hotel = Hotel.objects.get(id=id)
    if request.user.is_authenticated:
        bookmark = Bookmark.objects.filter(user=request.user, hotel=hotel)
        if bookmark.exists():
            bookmark = Bookmark.objects.get(user=request.user, hotel=hotel)
            bookmark.delete()
            return JsonResponse({"data":"Bookmark Deleted", "icon":"success"})
        else:
            Bookmark.objects.create(user=request.user, hotel=hotel)
            return JsonResponse({"data":"Hotel Bookmarked" , "icon":"success"})
    else:
        return JsonResponse({"data":"Login To Bookmark Hotel" , "icon":"warning"})


@login_required
def profile(request):
    profile = Profile.objects.get(user=request.user)

    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)

        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, "Profile Updated Successfully")
            return redirect("dashboard:profile")
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    
    context = {
        "profile":profile,
        "u_form":u_form,
        "p_form":p_form,
    }
    return render(request, "user_dashboard/profile.html", context)


@login_required
def password_changed(request):
    return render(request, "user_dashboard/password_changed.html")


@login_required
def add_review(request):
    id = request.GET['id']
    rating = request.GET['rating']
    review = request.GET['review']
    hotel = Hotel.objects.get(id=id)

    review_check = Review.objects.filter(user=request.user, hotel=hotel)
    if review_check.exists():
        return JsonResponse({"data":"Review Already Exists", "icon":"warning"})
    else:
        Review.objects.create(
            user=request.user,
            rating=rating,
            hotel=hotel,
            review=review
        )
        return JsonResponse({"data":"Review Submitted, Thank You." , "icon":"success"})

templates/user_dashboard/bookings.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

    <!-- Dashboard -->
    <div id="dashboard">
        <a href="#" class="utf_dashboard_nav_responsive"><i class="fa fa-reorder"></i> Dashboard Sidebar Menu</a>
        {% include 'partials/dashboard_sidebar.html' %}
        <div class="utf_dashboard_content">
            
           
            <div class="row"> 
                <div class="col-lg-12 col-md-12">
                  <div class="utf_dashboard_list_box margin-top-0">
                    <div class="sort-by my_sort_by">
                        <div class="utf_sort_by_select_item">
                          <select data-placeholder="All Listing" class="utf_chosen_select_single">
                            <option>All Orders</option>
                            <option>Paid Orders</option>
                            <option>UPaid Orders</option>
                            
                          </select>
                        </div>
                    </div>
                    <h4>All Bookings</h4>
                    <ul>
                        
                        {% for b in bookings %}
                            <li class="utf_approved_booking_listing">
                                <div class="utf_list_box_listing_item bookings">
                                <div class="utf_list_box_listing_item_content">
                                    <div class="inner">
                                    <h3>{{b.full_name|title}} <span class="utf_booking_listing_status">{{b.payment_status|title}}</span></h3>
                                    <div class="utf_inner_booking_listing_list">
                                        <h5>Booking Item: </h5>
                                        <ul class="utf_booking_listing_list">
                                        <li>{{b.hotel.name}}</li>						  						  
                                        </ul>
                                    </div>
                                    <div class="utf_inner_booking_listing_list">
                                        <h5>Checkin Date:</h5>
                                        <ul class="utf_booking_listing_list">
                                          <li class="highlighted">{{b.check_in_date}}</li>
                                        </ul>
                                      </div>
                                      <div class="utf_inner_booking_listing_list">
                                        <h5>Checkout Date:</h5>
                                        <ul class="utf_booking_listing_list">
                                          <li class="highlighted">{{b.check_out_date}}</li>
                                        </ul>
                                      </div>
                                      <div class="utf_inner_booking_listing_list">
                                        <h5>Total Days:</h5>
                                        <ul class="utf_booking_listing_list">
                                          <li class="highlighted">{{ b.total_days }} Days</li>
                                        </ul>
                                      </div>
                                      <div class="utf_inner_booking_listing_list">
                                        <h5>Adults:</h5>
                                        <ul class="utf_booking_listing_list">
                                          <li class="highlighted">{{ b.num_adults }} Adults</li>
                                        </ul>
                                      </div>
                                      <div class="utf_inner_booking_listing_list">
                                        <h5>Children:</h5>
                                        <ul class="utf_booking_listing_list">
                                          <li class="highlighted">{{ b.num_children }} Adults</li>
                                        </ul>
                                      </div>
                                   
                                    <div class="utf_inner_booking_listing_list">
                                        <h5>Price:</h5>
                                        <ul class="utf_booking_listing_list">
                                            <li class="highlighted">${{b.total|floatformat:2}}</li>
                                        </ul>
                                    </div>					  					  
                                    </div>
                                </div>
                                </div>
                                <div class=""> <a href="{% url 'dashboard:booking_detail' b.booking_id %}" class="button gray reject"><i class="fas fa-eye"></i> View Booking Detail</a> </div>
                            </li>
                        {% endfor %}
                      
                    </ul>
                  </div>		  
                </div>
              </div>
        </div>
    </div>
{% endblock content %}

templates/user_dashboard/bookmark.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}
<div id="dashboard">
    <a href="#" class="utf_dashboard_nav_responsive"><i class="fa fa-reorder"></i> Dashboard Sidebar Menu</a>
    {% include 'partials/dashboard_sidebar.html' %}
    <div class="utf_dashboard_content">
        
       
        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="utf_dashboard_list_box margin-top-0">
                    <h4><i class="fas fa-heart"></i> All Bookmarked Hotels</h4>
                    <ul>
                        
                        {% for b in bookmark %}
                            <li>
                                <div class="utf_list_box_listing_item">
                                    <div class="utf_list_box_listing_item-img">
                                        <a href="{% url 'hotel:detail' b.hotel.slug %}"><img src="{{b.hotel.image.url}}" alt=""></a>
                                    </div>
                                    <div class="utf_list_box_listing_item_content">
                                        <div class="inner">
                                            <h3>{{b.hotel.name}}</h3>
                                            <span><i class="fa fa-map-marker"></i> {{b.hotel.address}}</span>
                                            <span><i class="fa fa-envelope"></i> {{b.hotel.email}}</span>
                                            <span><i class="fa fa-phone"></i> {{b.hotel.mobile}}</span>
                                            <div class="utf_star_rating_section">
                                                <div class="utf_counter_star_rating">(4.5)</div>
                                                <span class="star"></span>
                                                <span class="star"></span>
                                                <span class="star"></span>
                                                <span class="star half"></span>
                                                <span class="star empty"></span>
                                            </div>
                                        </div>
                                    </div>
                                    <div> <a href="{% url 'dashboard:delete_bookmark' b.bid %}" class="button gray"><i class="fas fa-trash" style="color: red;"></i> Delete</a> </div>
                                </div>
                            </li>
                        {% empty %}
                        <li>
                            <h6>No Bookmarks Yet</h6>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

templates/user_dashboard/dashboard.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

    <!-- Dashboard -->
    <div id="dashboard">
        <a href="#" class="utf_dashboard_nav_responsive"><i class="fa fa-reorder"></i> Dashboard Sidebar Menu</a>
        {% include 'partials/dashboard_sidebar.html' %}
        <div class="utf_dashboard_content">
            
            <div class="row">
                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="utf_dashboard_stat color-1">
                        <div class="utf_dashboard_stat_content">
                            <h4>{{bookings.count}}</h4>
                            <span>Total Paid Bookings</span>
                        </div>
                        <div class="utf_dashboard_stat_icon"><i class="fas fa-check"></i></div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="utf_dashboard_stat color-2">
                        <div class="utf_dashboard_stat_content">
                            <h4>${{total_spent.amount|floatformat:2}}</h4>
                            <span>Total Spent</span>
                        </div>
                        <div class="utf_dashboard_stat_icon"><i class="fas fa-dollar"></i></div>
                    </div>
                </div>

                <div class="col-lg-4 col-md-12 col-sm-12">
                    <div class="utf_dashboard_stat color-3">
                        <div class="utf_dashboard_stat_content">
                            <h4>${{request.user.profile.wallet|floatformat:2}}</h4>
                            <span>Wallet Balance</span>
                        </div>
                        <div class="utf_dashboard_stat_icon"><i class="fas fa-wallet"></i></div>
                    </div>
                </div>

            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 mb-4">
                    <div class="utf_dashboard_list_box table-responsive recent_booking">
                        <h4>Booking</h4>
                        <div class="dashboard-list-box table-responsive invoices with-icons">
                            <table class="table table-hover">
                                <thead>
                                    <tr>
                                        <th>S/N</th>
                                        <th>Hotel Name</th>
                                        <th>Total Rooms</th>
                                        <th>Booking Date</th>
                                        <th>Payment Status</th>
                                        <th>View Booking</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                    {% for b in bookings %}
                                        <tr>
                                            <td>1</td>
                                            <td>{{ b.hotel.name }}</td>
                                            <td>{{ b.room.all.count }}</td>
                                            <td>{{b.date}}</td>
                                            <td><span class="badge text-uppercase">{{ b.payment_status }}</span></td>
                                            <td><a href="{% url 'dashboard:booking_detail' b.booking_id %}" class="button gray"><i class="fa fa-eye"></i> View</a></td>
                                        </tr>
                                    {% endfor %}
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <div class="col-lg-12 col-md-12">
                    <div class="utf_dashboard_list_box invoices with-icons margin-top-20">
                        <h4>All Booking Invoices</h4>
                        <ul>
                            
                            {% for b in bookings %}
                                <li><i class="fas fa-receipt"></i> <strong>{{b.hotel.name}} <span class="paid">{{b.payment_status|title}}</span></strong>
                                    <ul>
                                        <li><span>Order Number:-</span> {{b.booking_id}}</li>
                                        <li><span>Date:-</span> {{b.date|date:"d M, Y"}}</li>
                                    </ul>
                                    <div class="buttons-to-right"> <a href="{% url 'hotel:invoice' b.booking_id %}" class="button gray"><i class="fas fa-arrow-right"></i> Invoice</a> </div>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user_dashboard/notifications.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

    <!-- Dashboard -->
    <div id="dashboard">
        <a href="#" class="utf_dashboard_nav_responsive"><i class="fa fa-reorder"></i> Dashboard Sidebar Menu</a>
        {% include 'partials/dashboard_sidebar.html' %}
        <div class="utf_dashboard_content ">
            
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="utf_dashboard_list_box with-icons margin-top-20 noti-div-main">
                        <div class="sort-by my_sort_by">
                            <div class="utf_sort_by_select_item">
                              <select id="noti-status" data-placeholder="All Listing" class="utf_chosen_select_single">
                                <option value="all">All Notifications</option>
                                <option value="read">Read Notifications</option>
                                <option value="unread">Unread Notifications</option>
                                
                              </select>
                            </div>
                        </div>
                        <h4 class="noti-text">Notifications</h4>
                        
                        <ul class="">
                            
                            {% for n in notifications %}
                                <li class="noti-div-{{n.id}}">
                                    {% if n.type == "Booking Confirmed" %}
                                         Your booking (#{{n.booking.booking_id}}) has been placed successfully. <a href="#" data-index="{{n.id}}"  id=""  class=" noti-{{n.id}} close-list-item mark-noti-as-seen"><i class="fa fa-close"></i></a>
                                    {% endif %}

                                    {% if n.type == "Booking Cancelled" %}
                                         Your booking (#{{n.booking.booking_id}}) has been cancelled. <a href="#"  data-index="{{n.id}}" id=""  class=" noti-{{n.id}} close-list-item mark-noti-as-seen"><i class="fa fa-close"></i></a>
                                    {% endif %}
                                </li>
                                {% empty %}
                                        <li>
                                            <h6>No Notifications Yet</h6>
                                        </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/user_dashboard/password_changed.html
{% extends 'partials/dashboard_base.html' %}
{% load static %}
{% block content %}

    <div id="dashboard">
        <a href="#" class="utf_dashboard_nav_responsive"><i class="fa fa-reorder"></i> Dashboard Sidebar Menu</a>
        {% include 'partials/dashboard_sidebar.html' %}
        <div class="utf_dashboard_content">
            <div class="row"> 
                <div class="col-lg-12 col-md-12">
                  <div class="utf_dashboard_list_box margin-top-0">
                    <h4 class="gray"><i class="fas fa-check-circle"></i> Password Changed Successfully</h4>
                  </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}