booking/urls.py
from django.urls import path 
from booking import views 

app_name = "booking"

urlpatterns = [
    path("check_room_availability/", views.check_room_availability, name="check_room_availability"),
    path("delete_session/", views.delete_session, name="delete_session"),
    path("booking_data/<slug:slug>/", views.booking_data, name="booking_data"),

    # Ajax
    path("add_to_selection/", views.add_to_selection, name="add_to_selection"),
    path("delete_selection/", views.delete_selection, name="delete_selection"),
    
]

hotel/urls.py
from django.urls import path 
from hotel import views 

app_name = "hotel"

urlpatterns = [
    path("", views.index, name="index"),
    path("detail/<slug:slug>/", views.hotel_detail, name="detail"),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>/", views.room_type_detail, name="room_type_detail"),
    path("selected_rooms/", views.selected_rooms, name="selected_rooms"),
    path("checkout/<booking_id>/", views.checkout, name="checkout"),
    path("invoice/<booking_id>/", views.invoice, name="invoice"),
    path("update_room_status/", views.update_room_status, name="update_room_status"),
    
    # Payment API
    path('api/checkout-session/<booking_id>/', views.create_checkout_session, name='api_checkout_session'),
    path('success/<booking_id>/', views.payment_success, name='success'),
    path('failed/<booking_id>/', views.payment_failed, name='failed'),
]

hotel_management/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from  django.views.static import serve
from django.contrib.staticfiles.urls import staticfiles_urlpatterns # new
from django.views.static import serve


urlpatterns = [
    path('admin/', admin.site.urls),

    # Apps Routes
    path("", include("hotel.urls")),
    path("booking/", include("booking.urls")),
    path("user/", include("userauths.urls")),
    path("dashboard/", include("user_dashboard.urls")),


    #path("media/)", serve,{'document_root': settings.MEDIA_ROOT}),
    #path("static/)", serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]


#if settings.DEBUG:
#urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booking/models.py
from django.db import models

# Create your models here.

booking/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.template.loader import render_to_string


from hotel.models import Hotel, Room, Booking, RoomServices, HotelGallery, HotelFeatures, RoomType

from datetime import datetime
from decimal import Decimal

def check_room_availability(request):
    if request.method == "POST":
        id = request.POST.get("hotel-id")
        checkin = request.POST.get("checkin")
        checkout = request.POST.get("checkout")
        adult = request.POST.get("adult")
        children = request.POST.get("children")
        room_type = request.POST.get("room-type")

        hotel = Hotel.objects.get(status="Live", id=id)
        room_type = RoomType.objects.get(hotel=hotel, slug=room_type)
        
        print("id ====", id)
        print("room_type ====", room_type)
        print("checkin ====", checkin)
        print("checkout ====", checkout)
        print("adult ====", adult)
        print("children ====", children)

        # return redirect("hotel:room_type_detail", hotel.slug, room_type.slug)
        url = reverse("hotel:room_type_detail", args=[hotel.slug, room_type.slug])
        url_with_params = f"{url}?hotel-id={id}&checkin={checkin}&checkout={checkout}&adult={adult}&children={children}&room_type={room_type}"
        return HttpResponseRedirect(url_with_params)

    else:
        return redirect("hotel:index")


def booking_data(request, slug):
    hotel = Hotel.objects.get(status="Live", slug=slug)
    context = {
        "hotel":hotel,
    }
    return render(request, "booking/booking_data.html", context)


def add_to_selection(request):
    room_selection = {}

    room_selection[str(request.GET['id'])] = {
        'hotel_id': request.GET['hotel_id'],
        'hotel_name': request.GET['hotel_name'],
        'room_name': request.GET['room_name'],
        'room_price': request.GET['room_price'],
        'number_of_beds': request.GET['number_of_beds'],
        'room_number': request.GET['room_number'],
        'room_type': request.GET['room_type'],
        'room_id': request.GET['room_id'],
        'checkin': request.GET['checkin'],
        'checkout': request.GET['checkout'],
        'adult': request.GET['adult'],
        'children': request.GET['children'],
    }

    if 'selection_data_obj' in request.session:
        if str(request.GET['id']) in request.session['selection_data_obj']:

            selection_data = request.session['selection_data_obj']
            selection_data[str(request.GET['id'])]['adult'] = int(room_selection[str(request.GET['id'])]['adult'])
            selection_data[str(request.GET['id'])]['children'] = int(room_selection[str(request.GET['id'])]['children'])
            request.session['selection_data_obj'] = selection_data
        else:
            selection_data = request.session['selection_data_obj']
            selection_data.update(room_selection)
            request.session['selection_data_obj'] = selection_data
    else:
        request.session['selection_data_obj'] = room_selection
    data = {
        "data":request.session['selection_data_obj'], 
        'total_selected_items': len(request.session['selection_data_obj'])
        }
    return JsonResponse(data)


def delete_session(request):
    request.session.pop('selection_data_obj', None)
    return redirect(request.META.get("HTTP_REFERER"))


def delete_selection(request):
    hotel_id = str(request.GET['id'])
    if 'selection_data_obj' in request.session:
        if hotel_id in request.session['selection_data_obj']:
            selection_data = request.session['selection_data_obj']
            del request.session['selection_data_obj'][hotel_id]
            request.session['selection_data_obj'] = selection_data


    total = 0
    total_days = 0
    room_count = 0
    adult = 0 
    children = 0 
    checkin = "" 
    checkout = "" 
    children = 0 
    hotel = None

    if 'selection_data_obj' in request.session:
        for h_id, item in request.session['selection_data_obj'].items():
                
            id = int(item['hotel_id'])

            checkin = item["checkin"]
            checkout = item["checkout"]
            adult += int(item["adult"])
            children += int(item["children"])
            room_type_ = item["room_type"]
            
            hotel = Hotel.objects.get(id=id)
            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = datetime.strptime(checkin, date_format)
            checout_date = datetime.strptime(checkout, date_format)
            time_difference = checout_date - checkin_date
            total_days = time_difference.days

            room_count += 1
            days = total_days
            price = room_type.price

            room_price = price * room_count
            total = room_price * days
        
    
    context = render_to_string("hotel/async/selected_rooms.html", { "data":request.session['selection_data_obj'],  "total_selected_items": len(request.session['selection_data_obj']), "total":total, "total_days":total_days, "adult":adult, "children":children,    "checkin":checkin,    "checkout":checkout,    "hotel":hotel})

    print("data ======", context)
    
    return JsonResponse({"data": context, 'total_selected_items': len(request.session['selection_data_obj'])})

templates/booking/booking_data.html
{% extends 'partials/base.html' %}
{% load static %}
{% block content %}
  
  <div id="titlebar" class="gradient">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <h2>Select Booking Data</h2>
        </div>
      </div>
    </div>
  </div>

  
  <section class="fullwidth_block margin-top-0 padding-top-0 padding-bottom-50" data-background-color="#fff"> 
    <div class="container">
      
      <div class="row d-flex justify-content-center" style="display: flex; justify-content: center;">  
        <div class="col-lg-6">
            <div class=" booking_widget_box" style="border: 1px dashed rgba(42, 1, 119, 0.61); padding: 14px; border-radius: 10px;">
              <h3><i class="fa fa-calendar"></i> Booking</h3>
              <form class="row with-forms margin-top-0" method="POST" action="{% url 'booking:check_room_availability' %}">
                {% csrf_token %}
                <input type="hidden" value="{{hotel.id}}" name="hotel-id" id="">
                <div class="col-lg-12 col-md-12 select_date_box">
                    <label for="">Check-in Date</label>
                    <input type="date" id="date-picker" name="checkin" placeholder="Select Date">
                </div>
                <div class="col-lg-12 col-md-12 select_date_box">
                    <label for="">Check-out Date</label>
                    <input type="date" name="checkout" id="date-picker" placeholder="Select Date">
                </div>
                <div class="with-forms">
                    <div class="col-lg-12 col-md-12">
                        <a href="#">Guests <span class="qtyTotal" name="qtyTotal">1</span></a>
                        <div class="panel-dropdown-content">
                            <div class="qtyButtons">
                                <div class="qtyTitle">Adults</div>
                                <input type="text" name="adult" value="1">
                            </div>
                            <div class="qtyButtons">
                                <div class="qtyTitle">Childrens</div>
                                <input type="text" name="children" value="1">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="with-forms margin-top-30">
                    <div class="col-lg-12 col-md-12 ">
                        <a href="#">Select Room Type</a>
                        <select name="room-type" class="utf_chosen_select_single" required>
                            <option value="">Select Room</option>
                            {% for r in hotel.hotel_room_types %}
                                <option value="{{r.slug}}">{{r.type}}</option>
                            {% endfor %}
                          </select>
                    </div>
                </div>
               
                <button type="submit" class="utf_progress_button button fullwidth_block margin-top-5">Check Availability</button>
            </form>
              <button class="like-button add_to_wishlist"><span class="like-icon"></span> Add to Wishlist</button>
              <div class="clearfix"></div>
            </div>
        </div>      
      </div>      
    </div>    
  </section>


  
{% endblock content %}